from yacs.config import CfgNode as CN

_C = CN()
_C.OUTPUT_DIR = "yelp_recommendation/output"
_C.DATA_ROOT = "yelp_recommendation/datasets/"
_C.DATA_JSON = "extracted_yelp_dataset_review.json"
_C.SEED = -1
_C.CUDNN_BENCHMARK = False
_C.IS_TRAIN = True
_C.IS_PREPROCESSED = True

_C.DATASET_MAPPER = CN()
_C.DATASET_MAPPER.ATTRIB_DICT = []

_C.DATALOADER = CN()
_C.DATALOADER.NUM_WORKERS = 4

_C.MODEL = CN()
_C.MODEL.NAME = "NaiveCF"
_C.MODEL.DEVICE = "cuda"
_C.MODEL.WEIGHTS = None

_C.MODEL.CF = CN()
_C.MODEL.CF.LATENT_SIZE = 5

_C.MODEL.SHARED_CF = CN()
_C.MODEL.SHARED_CF.NUM_FC = 2

_C.STATISTICS = CN()
_C.STATISTICS.USER_SIZE = 10
_C.STATISTICS.ITEM_SIZE = 10

_C.SOLVER = CN()
_C.SOLVER.LR_SCHEDULER_NAME = "WarmupMultiStepLR"
_C.SOLVER.MAX_ITER = 5000
_C.SOLVER.BASE_LR = 0.01
_C.SOLVER.MOMENTUM = 0.9
_C.SOLVER.NESTEROV = False
_C.SOLVER.WEIGHT_DECAY = 0.01
_C.SOLVER.WEIGHT_DECAY_NORM = 0.0
_C.SOLVER.GAMMA = 0.1
_C.SOLVER.STEPS = (1000,)
_C.SOLVER.WARMUP_FACTOR = 1.0 / 1000
_C.SOLVER.WARMUP_ITERS = 100
_C.SOLVER.WARMUP_METHOD = "linear"
_C.SOLVER.CHECKPOINT_PERIOD = 500
_C.SOLVER.REVIEW_PER_BATCH = 256
_C.SOLVER.BIAS_LR_FACTOR = 1.0
_C.SOLVER.WEIGHT_DECAY_BIAS = _C.SOLVER.WEIGHT_DECAY
_C.SOLVER.CLIP_GRADIENTS = CN({"ENABLED": False})
_C.SOLVER.CLIP_GRADIENTS.CLIP_TYPE = "value"
_C.SOLVER.CLIP_GRADIENTS.CLIP_VALUE = 1.0
_C.SOLVER.CLIP_GRADIENTS.NORM_TYPE = 2.0


_C.TEST = CN()
_C.TEST.EVAL_PERIOD = -1
