OUTPUT_DIR: "yelp_recommendation/output/base_config"
DATA_ROOT: "yelp_recommendation/datasets/"
#DATA_JSON: "yelp_academic_dataset_review.json"
DATA_JSON: "extracted_yelp_dataset_review.json"
SEED: 0
IS_TRAIN: True
IS_PREPROCESSED: True
DATASET_MAPPER:
  ATTRIB_DICT: ['user_id', 'business_id', 'stars']
DATALOADER:
  NUM_WORKERS: 24
MODEL:
  NAME: 'NaiveCF'